name: Run tests

on:
  repository_dispatch:
    types: [run-tests]
  
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      VERSION: latest
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Install Dependencies
      run: npm install

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Spin up all services
    - name: Start services
      run: ./scripts/cd/run-docker-compose.sh

    # Wait for services to be ready
    - name: Wait for services
      run: sleep 30 # This is a temporary solution

    # Run Playwright tests
    - name: Run Playwright tests
      run: npm run test

    # Tear down services after tests
    - name: Tear down
      run: docker compose down

    - name: Trigger Deployment Pipeline
      if: ${{ success() }}
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/daosgava/daniel-garcia-sit772-10-hd/dispatches \
          -d '{"event_type":"deploy-gateway"}'
