name: Run Integration Tests

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Install Docker Compose
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Spin up all services
    - name: Start services
      run: docker-compose up -d

    # Wait for services to be ready
    - name: Wait for services
      run: sleep 30 # Adjust based on how long your services take to start

    # Run Playwright tests
    - name: Run Playwright tests
      run: npm run test

    # Tear down services after tests
    - name: Tear down
      run: docker-compose down
